language: java
sudo: false

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: trusty
      jdk: openjdk8
      env: BROWSERS=ChromeHeadlessNoSandbox,FirefoxHeadless

addons:
  chrome: stable
  firefox: latest

before_install:
  - nvm i node
  - npm ci

script :
  - npm run build-static
  - npm test -- --browsers $BROWSERS
  - npm run lint-js
  - npm run lint-css
  - npm run lint-md
  - mvn license:check
  - mvn clean install

cache:
  directories:
    - $HOME/.m2
    - $HOME/.npm
