language: java

sudo: false

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: trusty
      jdk: oraclejdk8
      env: BROWSERS=ChromeHeadless,FirefoxHeadless
    - os: linux
      dist: trusty
      jdk: openjdk7
      env: BROWSERS=ChromeHeadless,FirefoxHeadless
    - os: osx
      osx_image: xcode8.3
      env: BROWSERS=ChromeHeadless,Safari

addons:
  chrome: stable
  firefox: latest

before_install:
  - nvm i node
  - npm install
  - npm install -g greenkeeper-lockfile@1

before_script: greenkeeper-lockfile-update

script :
  - npm run build-static
  - npm test -- --browsers $BROWSERS
  - npm run lint-js
  - npm run lint-css
  - npm run lint-md
  - mvn license:check
  - mvn clean install

cache:
  directories:
    - $HOME/.m2
    - $HOME/.npm
