dist: trusty
language: java
jdk:
  - openjdk7
  - oraclejdk8
addons:
  chrome: stable
sudo: false
before_install:
  - nvm i node
  - npm install
script :
  - npm run build-static
  - npm test
  - npm run lint-js
  - cd uw-frame-java/
  - mvn clean install
cache:
  directories:
    - $HOME/.m2
    - $HOME/.npm
