language: java

sudo: false

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: trusty
      jdk: oraclejdk8
    - os: linux
      dist: trusty
      jdk: openjdk7
    - os: osx
      osx_image: xcode8.3

addons:
  chrome: stable

before_install:
  - nvm i node
  - npm install
  - npm install -g greenkeeper-lockfile@1

before_script: greenkeeper-lockfile-update

script :
  - npm run build-static
  - npm test
  - npm run lint-js
  - npm run lint-css
  - npm run lint-md
  - mvn license:check
  - mvn clean install

after_script: greenkeeper-lockfile-upload

cache:
  directories:
    - $HOME/.m2
    - $HOME/.npm
